/************************************************************************************************
** File created by QxEntityEditor 1.2.6 (2021/12/24 17:39) : please, do NOT modify this file ! **
************************************************************************************************/

#ifndef _MYSCOOL_SIMAT_H_
#define _MYSCOOL_SIMAT_H_
#include <QString>
#include <QList>
#include "precompiled.h"
#include <QxRegister/QxRegister.h>
#include "student.h"
class ORM_MYSCHOOL_EXPORT simat
{

   QX_REGISTER_FRIEND_CLASS(simat)

protected:

   long m_rowid; //!< Auto-generated by QxEntityEditor importer because there is no id defined
   long m_ANO;
   QString m_ESTADO;
   long m_CODIGO_JERARQUIA;
   QString m_JERARQUIA;
   QString m_INSTITUCION;
   long m_DANE;
   QString m_CALENDARIO;
   QString m_SECTOR;
   QString m_SEDE;
   long m_CONSECUTIVO;
   QString m_JORNADA;
   QString m_GRADO;
   long m_GRADO_COD;
   long m_GRUPO;
   QString m_MODELO;
   long m_MOTIVO;
   QString m_FECHAINI;
   long m_FECHAFIN;
   QString m_NUI;
   QString m_ESTRATO;
   long m_SISBEN_TRES;
   QString m_DOC;
   QString m_TIPODOC;
   QString m_APELLIDO1;
   QString m_APELLIDO2;
   QString m_NOMBRE1;
   QString m_NOMBRE2;
   QString m_GENERO;
   long m_EDAD;
   QString m_MATRICULACONTRATADA;
   QString m_FUENTE_RECURSOS;
   QString m_INTERNADO;
   student_ptr m_student;

public:

   simat();
   simat(const long & id);
   virtual ~simat();
     long getrowid() const;
   long getANO() const;
   QString getESTADO() const;
   long getCODIGO_JERARQUIA() const;
   QString getJERARQUIA() const;
   QString getINSTITUCION() const;
   long getDANE() const;
   QString getCALENDARIO() const;
   QString getSECTOR() const;
   QString getSEDE() const;
   long getCONSECUTIVO() const;
   QString getJORNADA() const;
   QString getGRADO() const;
   long getGRADO_COD() const;
   long getGRUPO() const;
   QString getMODELO() const;
   long getMOTIVO() const;
   QString getFECHAINI() const;
   long getFECHAFIN() const;
   QString getNUI() const;
   QString getESTRATO() const;
   long getSISBEN_TRES() const;
   QString getDOC() const;
   QString getTIPODOC() const;
   QString getAPELLIDO1() const;
   QString getAPELLIDO2() const;
   QString getNOMBRE1() const;
   QString getNOMBRE2() const;
   QString getGENERO() const;
   long getEDAD() const;
   QString getMATRICULACONTRATADA() const;
   QString getFUENTE_RECURSOS() const;
   QString getINTERNADO() const;

    void setrowid(const long & val);
   void setANO(const long & val);
   void setESTADO(const QString & val);
   void setCODIGO_JERARQUIA(const long & val);
   void setJERARQUIA(const QString & val);
   void setINSTITUCION(const QString & val);
   void setDANE(const long & val);
   void setCALENDARIO(const QString & val);
   void setSECTOR(const QString & val);
   void setSEDE(const QString & val);
   void setCONSECUTIVO(const long & val);
   void setJORNADA(const QString & val);
   void setGRADO(const QString & val);
   void setGRADO_COD(const long & val);
   void setGRUPO(const long & val);
   void setMODELO(const QString & val);
   void setMOTIVO(const long & val);
   void setFECHAINI(const QString & val);
   void setFECHAFIN(const long & val);
   void setNUI(const QString & val);
   void setESTRATO(const QString & val);
   void setSISBEN_TRES(const long & val);
   void setDOC(const QString & val);
   void setTIPODOC(const QString & val);
   void setAPELLIDO1(const QString & val);
   void setAPELLIDO2(const QString & val);
   void setNOMBRE1(const QString & val);
   void setNOMBRE2(const QString & val);
   void setGENERO(const QString & val);
   void setEDAD(const long & val);
   void setMATRICULACONTRATADA(const QString & val);
   void setFUENTE_RECURSOS(const QString & val);
   void setINTERNADO(const QString & val);

public:
    static QString column_rowid(bool key = false) { Q_UNUSED(key); return "rowid"; }
   static QString column_ANO(bool key = false) { Q_UNUSED(key); return "ANO"; }
   static QString column_ESTADO(bool key = false) { Q_UNUSED(key); return "ESTADO"; }
   static QString column_CODIGO_JERARQUIA(bool key = false) { Q_UNUSED(key); return "CODIGO_JERARQUIA"; }
   static QString column_JERARQUIA(bool key = false) { Q_UNUSED(key); return "JERARQUIA"; }
   static QString column_INSTITUCION(bool key = false) { Q_UNUSED(key); return "INSTITUCION"; }
   static QString column_DANE(bool key = false) { Q_UNUSED(key); return "DANE"; }
   static QString column_CALENDARIO(bool key = false) { Q_UNUSED(key); return "CALENDARIO"; }
   static QString column_SECTOR(bool key = false) { Q_UNUSED(key); return "SECTOR"; }
   static QString column_SEDE(bool key = false) { Q_UNUSED(key); return "SEDE"; }
   static QString column_CONSECUTIVO(bool key = false) { Q_UNUSED(key); return "CONSECUTIVO"; }
   static QString column_JORNADA(bool key = false) { Q_UNUSED(key); return "JORNADA"; }
   static QString column_GRADO(bool key = false) { Q_UNUSED(key); return "GRADO"; }
   static QString column_GRADO_COD(bool key = false) { Q_UNUSED(key); return "GRADO_COD"; }
   static QString column_GRUPO(bool key = false) { Q_UNUSED(key); return "GRUPO"; }
   static QString column_MODELO(bool key = false) { Q_UNUSED(key); return "MODELO"; }
   static QString column_MOTIVO(bool key = false) { Q_UNUSED(key); return "MOTIVO"; }
   static QString column_FECHAINI(bool key = false) { Q_UNUSED(key); return "FECHAINI"; }
   static QString column_FECHAFIN(bool key = false) { Q_UNUSED(key); return "FECHAFIN"; }
   static QString column_NUI(bool key = false) { Q_UNUSED(key); return "NUI"; }
   static QString column_ESTRATO(bool key = false) { Q_UNUSED(key); return "ESTRATO"; }
   static QString column_SISBEN_TRES(bool key = false) { Q_UNUSED(key); return "SISBEN_TRES"; }
   static QString column_DOC(bool key = false) { Q_UNUSED(key); return "DOC"; }
   static QString column_TIPODOC(bool key = false) { Q_UNUSED(key); return "TIPODOC"; }
   static QString column_APELLIDO1(bool key = false) { Q_UNUSED(key); return "APELLIDO1"; }
   static QString column_APELLIDO2(bool key = false) { Q_UNUSED(key); return "APELLIDO2"; }
   static QString column_NOMBRE1(bool key = false) { Q_UNUSED(key); return "NOMBRE1"; }
   static QString column_NOMBRE2(bool key = false) { Q_UNUSED(key); return "NOMBRE2"; }
   static QString column_GENERO(bool key = false) { Q_UNUSED(key); return "GENERO"; }
   static QString column_EDAD(bool key = false) { Q_UNUSED(key); return "EDAD"; }
   static QString column_MATRICULACONTRATADA(bool key = false) { Q_UNUSED(key); return "MATRICULACONTRATADA"; }
   static QString column_FUENTE_RECURSOS(bool key = false) { Q_UNUSED(key); return "FUENTE_RECURSOS"; }
   static QString column_INTERNADO(bool key = false) { Q_UNUSED(key); return "INTERNADO"; }

public:

   static QString table_name(bool key = false) { Q_UNUSED(key); return "simat"; }

};

typedef std::shared_ptr<simat> simat_ptr;
typedef QList<simat_ptr> list_of_simat;
typedef std::shared_ptr<list_of_simat> list_of_simat_ptr;

QX_REGISTER_COMPLEX_CLASS_NAME_HPP_ORM_MYSCHOOL(simat, qx::trait::no_base_class_defined, 0, simat)




#endif // _SIMA
