#ifndef _ORM_MYSCHOOL_MODEL_VIEW_PRECOMPILED_HEADER_H_CUSTOM
#define _ORM_MYSCHOOL_MODEL_VIEW_PRECOMPILED_HEADER_H_CUSTOM

#ifdef _MSC_VER
#pragma once
#endif

/* -- Put your custom code here -- */

#endif // _ORM_MYSCHOOL_MODEL_VIEW_PRECOMPILED_HEADER_H_CUSTOM
